[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Richard Rast <richard.rast@gmail.com>"]
edition = "2018"

[lib]
name = "bf_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "bf_interpreter"
path = "src/interpreter/main.rs"

[dependencies]
smallset = "0.1.1"
